#!/bin/sh
# unflab package installer.
#
# Installs one already-unpacked unflab package, driven entirely by the
# manifest embedded below. Generated by scripts/package.sh, which inlines
# utils/<name>/manifest.tsv at the marker below.
#
# Usage:
#   ./install.sh                        # into ~/.local/bin (default, no sudo)
#   ./install.sh --prefix /usr/local    # elsewhere (may need sudo)
#   ./install.sh --uninstall            # remove what this script installed
#   ./install.sh --purge                # uninstall, and remove config files too
#   ./install.sh --no-plain             # skip unprefixed-name symlinks
#   ./install.sh --quarantine           # also clear macOS's quarantine flag
#   ./install.sh --path / --no-path     # force PATH advice on/off (non-interactive)
#
# POSIX sh, and only tools present on a stock macOS: install, ln, sed,
# rm, readlink, command, xattr. Of `install` only -d and -m are used --
# the flags common to both BSD (macOS) and GNU install -- so this works
# regardless of which one is first on PATH.

set -eu

UTIL="{{UTIL}}"
VERSION="{{VERSION}}"

PREFIX="${HOME}/.local/bin"
WANT_PLAIN=1
WANT_QUARANTINE_CLEAR=0
ACTION=install
PATH_MODE=ask       # ask | yes | no

# ---------------------------------------------------------------- manifest

# Field order: kind <TAB> mode <TAB> source <TAB> dest <TAB> plain
# `-` means "not applicable". See scripts/templates/install.sh in the
# unflab repo for the format's definition.
MANIFEST=$(cat <<'UNFLAB_MANIFEST_EOF'
{{MANIFEST}}
UNFLAB_MANIFEST_EOF
)

# ---------------------------------------------------------------- arguments

# A leading `--` may or may not reach us: `sh -s -- --prefix=x` passes it
# through under sh/dash, while zsh consumes it. Tolerate either.
[ $# -gt 0 ] && [ "$1" = "--" ] && shift

while [ $# -gt 0 ]; do
  case "$1" in
    --prefix)     PREFIX="$2"; shift 2 ;;
    --prefix=*)   PREFIX="${1#--prefix=}"; shift ;;
    --uninstall)  ACTION=uninstall; shift ;;
    --purge)      ACTION=purge; shift ;;
    --no-plain)   WANT_PLAIN=0; shift ;;
    --quarantine) WANT_QUARANTINE_CLEAR=1; shift ;;
    --path)       PATH_MODE=yes; shift ;;
    --no-path)    PATH_MODE=no; shift ;;
    -h|--help)    sed -n '/^# Usage:/,/^$/p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *)            echo "install.sh: unknown option: $1" >&2; exit 2 ;;
  esac
done

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

# Everything hangs off the prefix's parent, matching the layout the
# package ships: <prefix>/bin, <prefix>/share/man/man1. Passing
# --prefix ~/.local/bin (a bin directory) is the documented interface,
# so derive the others from its parent.
BASE=$(dirname "$PREFIX")
MANDIR="$BASE/share/man/man1"
DOCDIR="$BASE/share/doc/$UTIL"
CONFDIR="${XDG_CONFIG_HOME:-$HOME/.config}/$UTIL"

installed_count=0
removed_count=0
skipped_plain=""
declined_stems=""

# ------------------------------------------------------------------ helpers

# Resolve a manifest `kind` to its destination directory and to whether
# --purge (rather than plain --uninstall) is what removes it.
dest_dir_for() {
  case "$1" in
    bin)        printf '%s' "$PREFIX" ;;
    man1)       printf '%s' "$MANDIR" ;;
    doc)        printf '%s' "$DOCDIR" ;;
    config)     printf '%s' "$CONFDIR" ;;
    completion) printf '%s' "$BASE/share/bash-completion/completions" ;;
    *)          return 1 ;;
  esac
}

# config files are user data: only --purge removes them, never --uninstall.
is_config_kind() { [ "$1" = "config" ]; }

# Remove a path only if we are sure it is ours. Two different rules,
# because we create these two kinds of entry differently:
#
#   remove_own_file  -- a file this package installed at its own name.
#                       A real file there is ours to remove.
#   remove_own_link  -- an unprefixed alias. We only ever create these as
#                       symlinks pointing at our own $dest, so a symlink
#                       elsewhere, or a REAL FILE, belongs to someone else
#                       and must be left strictly alone. Getting this
#                       wrong deletes another package's binary.
remove_own_file() {
  target="$1"
  [ -e "$target" ] || [ -L "$target" ] || return 0
  rm -f "$target"
  echo "Removed $target"
  removed_count=$((removed_count + 1))
}

remove_own_link() {
  target="$1"; expect="$2"
  # Not a symlink (missing, or a real file someone else owns) -> not ours.
  [ -L "$target" ] || {
    [ -e "$target" ] && echo "Kept $target (not ours: real file, not our symlink)"
    return 0
  }
  link=$(readlink "$target")
  case "$link" in
    "$expect"|*/"$expect") ;;
    *) echo "Kept $target (not ours: points at $link)"; return 0 ;;
  esac
  rm -f "$target"
  echo "Removed $target"
  removed_count=$((removed_count + 1))
}

# ------------------------------------------------------- uninstall / purge

if [ "$ACTION" = uninstall ] || [ "$ACTION" = purge ]; then
  # Fed by heredoc, NOT by a pipe: `echo "$MANIFEST" | while ...` runs the
  # loop in a subshell, so removed_count would be discarded and the
  # summary below would always report 0.
  while IFS='	' read -r kind mode src dest plain; do
    case "$kind" in ''|\#*) continue ;; esac
    dir=$(dest_dir_for "$kind") || continue

    # Config files survive --uninstall; only --purge takes them.
    if is_config_kind "$kind" && [ "$ACTION" != purge ]; then
      [ -e "$dir/$dest" ] && echo "Kept $dir/$dest (use --purge to remove)"
      continue
    fi

    # The plain-named alias first: it points at $dest, so verify before
    # removing the thing it points to.
    [ "$plain" != "-" ] && [ -n "$plain" ] && remove_own_link "$dir/$plain" "$dest"
    [ "$dest" != "-" ] && [ -n "$dest" ] && remove_own_file "$dir/$dest"
  done <<UNFLAB_EOF
$MANIFEST
UNFLAB_EOF

  # Only prune directories we own, and only when empty -- never $PREFIX
  # or $MANDIR, which belong to the user and hold other tools' files.
  for d in "$DOCDIR" "$CONFDIR"; do
    [ -d "$d" ] && rmdir "$d" 2>/dev/null && echo "Removed empty $d"
  done

  if [ "$removed_count" = 0 ]; then
    echo "Nothing to remove for $UTIL under $BASE."
  else
    echo ""
    echo "Removed $removed_count file(s) for $UTIL."
  fi
  exit 0
fi

# ------------------------------------------------------------------ install

while IFS='	' read -r kind mode src dest plain; do
  case "$kind" in ''|\#*) continue ;; esac
  dir=$(dest_dir_for "$kind") || { echo "install.sh: unknown kind '$kind'" >&2; exit 1; }
  [ "$dest" = "-" ] || [ -z "$dest" ] && continue

  if [ ! -f "$SCRIPT_DIR/$src" ]; then
    echo "install.sh: missing from package: $src" >&2
    exit 1
  fi

  # A config file is user data: never clobber one the user has edited.
  if is_config_kind "$kind" && [ -e "$dir/$dest" ]; then
    echo "Kept existing $dir/$dest (not overwritten)"
    continue
  fi

  install -d -m 755 "$dir"
  install -m "$mode" "$SCRIPT_DIR/$src" "$dir/$dest"
  echo "Installed $dir/$dest"
  installed_count=$((installed_count + 1))

  # The unprefixed alias, decided live on THIS machine rather than at
  # build time: claim the plain name only if nothing else answers to it.
  # `command -v` sees the real PATH, which is the only correct authority
  # on whether a name is already taken here.
  if [ "$WANT_PLAIN" = 1 ] && [ "$plain" != "-" ] && [ -n "$plain" ]; then
    if [ "$kind" = bin ]; then
      if command -v "$plain" >/dev/null 2>&1; then
        existing=$(command -v "$plain")
        # Our own earlier install doesn't count as a conflict.
        if [ "$existing" != "$dir/$plain" ]; then
          skipped_plain="$skipped_plain $plain"
          # Remember the *stem* so this binary's man page (and anything
          # else named after it) follows the same decision below.
          declined_stems="$declined_stems ${plain} "
          continue
        fi
      fi
    else
      # Non-binary kinds follow whatever the binary decided. `man demo`
      # must work exactly when a plain `demo` command exists to be asked
      # about -- otherwise we'd document a tool the user isn't running.
      stem=${plain%%.*}
      case "$declined_stems" in
        *" $stem "*)
          echo "Skipped $dir/$plain (plain '$stem' not claimed)"
          continue ;;
      esac
    fi
    # Relative target: the link sits beside its destination, so it keeps
    # resolving if the prefix is later moved, renamed, or reached by
    # another path (a symlinked home, a relocated tree).
    ln -sf "$dest" "$dir/$plain"
    echo "Installed $dir/$plain -> $dest"
  fi
done <<UNFLAB_EOF
$MANIFEST
UNFLAB_EOF

# --------------------------------------------------------------- quarantine

# Binaries here aren't signed with an Apple Developer ID or notarized, so
# if this package arrived via a browser (or anything else LaunchServices
# knows about) Gatekeeper will refuse to run it. `install` copies extended
# attributes along with the file, so the flag follows the binary to its
# destination -- which is why this is checked here, after the copy, and
# reported against the path you'll actually invoke.
#
# Downloads made by curl are NOT quarantined, so the `curl | sh` install
# path never hits this. It's the manual-download route that does.
#
# We don't clear it silently: that's a trust decision for you, not for a
# script to make on your behalf.
if command -v xattr >/dev/null 2>&1; then
  quarantined=""
  while IFS='	' read -r kind mode src dest plain; do
    case "$kind" in ''|\#*) continue ;; esac
    [ "$kind" = bin ] || continue
    [ "$dest" = "-" ] && continue
    if xattr -p com.apple.quarantine "$PREFIX/$dest" >/dev/null 2>&1; then
      if [ "$WANT_QUARANTINE_CLEAR" = 1 ]; then
        xattr -d com.apple.quarantine "$PREFIX/$dest" 2>/dev/null || true
        echo "Cleared com.apple.quarantine from $PREFIX/$dest"
      else
        quarantined="$quarantined $dest"
      fi
    fi
  done <<UNFLAB_EOF
$MANIFEST
UNFLAB_EOF

  if [ -n "$quarantined" ]; then
    echo ""
    echo "Note: macOS has quarantined the installed binary, and Gatekeeper"
    echo "      will block it. Re-run with --quarantine, or clear it yourself:"
    echo ""
    for q in $quarantined; do echo "          xattr -d com.apple.quarantine '$PREFIX/$q'"; done
    echo ""
  fi
fi

# --------------------------------------------------------------------- PATH

# Only PATH needs managing: macOS's `man` derives its own search path from
# PATH, finding <prefix>/../share/man automatically, so a working PATH
# gets the man pages for free and MANPATH never needs touching.
case ":$PATH:" in
  *":$PREFIX:"*) PATH_OK=1 ;;
  *)             PATH_OK=0 ;;
esac

if [ "$PATH_OK" = 0 ] && [ "$installed_count" -gt 0 ]; then
  # Pick the rc file for the user's login shell, not for whatever shell
  # happens to be running this script.
  case "${SHELL:-}" in
    */zsh)  RC="${ZDOTDIR:-$HOME}/.zshrc" ;;
    */bash) RC="$HOME/.bash_profile" ;;
    */fish) RC="$HOME/.config/fish/config.fish" ;;
    *)      RC="$HOME/.profile" ;;
  esac
  case "$RC" in
    */config.fish) LINE="fish_add_path $PREFIX" ;;
    *)             LINE="export PATH=\"$PREFIX:\$PATH\"" ;;
  esac

  echo ""
  echo "$PREFIX is not on your PATH, so '$UTIL' won't be found by name yet."

  # Interactivity is decided by *opening* /dev/tty, not by testing it.
  # Piped to `sh`, stdin is the script, so [ -t 0 ] is always false; and
  # [ -r /dev/tty ] passes even with no controlling terminal, where the
  # write then fails. Opening it read-write fails cleanly in both cases.
  # Probed in a subshell first because some shells treat a failed
  # redirection on `exec` as fatal to the whole script.
  TTY_OK=0
  if [ "$PATH_MODE" = ask ]; then
    if (exec 3<>/dev/tty) 2>/dev/null; then
      exec 3<>/dev/tty
      TTY_OK=1
    fi
  fi

  DO_PATH=0
  if [ "$PATH_MODE" = yes ]; then
    DO_PATH=1
  elif [ "$PATH_MODE" = ask ] && [ "$TTY_OK" = 1 ]; then
    echo "" >&3
    echo "  Add this line to $RC?" >&3
    echo "      $LINE" >&3
    printf '  [y/N] ' >&3
    IFS= read -r reply <&3 || reply=""
    case "$reply" in y|Y|yes|YES) DO_PATH=1 ;; esac
  fi

  if [ "$DO_PATH" = 1 ]; then
    # A marked block, so it's obvious who added this and easy to remove.
    {
      echo ""
      echo "# added by unflab ($UTIL)"
      echo "$LINE"
    } >> "$RC"
    echo "Added to $RC. Run:  . $RC   (or open a new terminal)"
  else
    echo ""
    echo "  To fix, add this to $RC:"
    echo "      $LINE"
    echo ""
    echo "  Or run it now for this shell only:"
    echo "      $LINE"
  fi
fi

# ------------------------------------------------------------------ summary

echo ""
if [ -n "$skipped_plain" ]; then
  for p in $skipped_plain; do
    echo "Note: '$p' already exists on this system ($(command -v "$p"))."
    echo "      Left it alone; use the installed name instead."
  done
  echo ""
fi
echo "$UTIL $VERSION installed ($installed_count file(s)) under $BASE."
