#!/bin/sh
#
# unflab package installer.
#
# Installs one already-unpacked unflab package, driven entirely by the
# manifest embedded below. Generated by scripts/package.sh, which inlines
# utils/<name>/manifest.tsv at the marker below.
#
# Usage:
#   ./install.sh                        # into ~/.local/bin (default, no sudo)
#   ./install.sh --prefix /usr/local    # elsewhere (may need sudo)
#   ./install.sh --uninstall            # remove what this script installed
#   ./install.sh --purge                # uninstall, and remove config files too
#   ./install.sh --no-plain             # skip unprefixed-name symlinks
#   ./install.sh --quarantine           # also clear macOS's quarantine flag
#   ./install.sh --path / --no-path     # force PATH advice on/off (non-interactive)
#
# POSIX sh, and only tools present on a stock macOS: install, ln, sed,
# rm, readlink, command, xattr. Of `install` only -d and -m are used --
# the flags common to both BSD (macOS) and GNU install -- so this works
# regardless of which one is first on PATH.

set -eu

# Terminal colours: default to none
TTY_OK=0
ESC=; RED=; GREEN=; YELLOW=; BLUE=; MAGENTA=; CYAN=
NORMAL=; BOLD=; NO_BOLD=; DIM=; ITALIC=; NO_ITALIC=; UNDERLINE=; NO_UNDERLINE=
RESET_COLOR=; RESET_STYLE=; RESET=
CO="<"; CC=">";
ELLIP="..."
NELLIP="   "

# Interactivity is decided by *opening* /dev/tty, not by testing it.
# Probed in a subshell first because some shells treat a failed
# redirection on `exec` as fatal to the whole script.
if (exec 3<>/dev/tty) 2>/dev/null; then
  exec 3<>/dev/tty
  TTY_OK=1
fi

# If we found a terminal, use colours.
if [ "$TTY_OK" = 1 ]; then
  ESC=$(printf '\033')
  RED="$ESC[91m";      GREEN="$ESC[92m";   YELLOW="$ESC[93m"
  BLUE="$ESC[94m";     MAGENTA="$ESC[95m"; CYAN="$ESC[96m"
  BOLD="$ESC[1m";      NO_BOLD="$ESC[22m"
  DIM="$ESC[2m";       NORMAL="$ESC[22m"
  ITALIC="$ESC[3m";    NO_ITALIC="$ESC[23m"
  UNDERLINE="$ESC[4m"; NO_UNDERLINE="$ESC[24m"
  RESET_COLOR="$ESC[39;49;9m"; RESET_STYLE="$ESC[29m"; RESET="$ESC[0m"
  CO="‹"; CC="›"; ELLIP="…"; NELLIP=" "
fi

SELF="${0##*/}"
WARNING="$MAGENTA"
ERROR="$RED"
FLAG="$GREEN"
COMMAND="$YELLOW"
PARAM="$BOLD$CYAN"
OPTIONAL="$DIM$CYAN"
COMMENT="$DIM # $ITALIC"

UTIL="{{UTIL}}"
VERSION="{{VERSION}}"

PREFIX="${HOME}/.local/bin"
WANT_PLAIN=1
WANT_QUARANTINE_CLEAR=0
ACTION=install
PATH_MODE=ask # ask | yes | no

# Manifest:
# Field order: kind <TAB> mode <TAB> source <TAB> dest <TAB> plain
# `-` means "not applicable". See scripts/templates/install.sh in the
# unflab repo for the format's definition.
MANIFEST=$(
  cat <<'UNFLAB_MANIFEST_EOF'
{{MANIFEST}}
UNFLAB_MANIFEST_EOF
)

# Post-install notes, printed after a successful install. Empty for most
# packages.
#
# Emitted from a function body rather than captured with
# `NOTES=$(cat <<'EOF' ... )`, because that construct cannot survive an
# apostrophe: the shell tokenises the whole of a $( ) BEFORE the heredoc
# body is taken literally, so one `'` in ordinary prose -- "the
# package's completions" -- opens a quote that never closes and the
# generated installer fails to parse. package.sh's `sh -n` check caught
# it, but only because a recipe happened to contain one; fzf's notes
# have no apostrophe and passed by luck. (`read -r -d '' NOTES` also
# fixes the quoting, but -d is a bashism dash rejects, and this script
# promises POSIX sh.)
#
# The quoted delimiter is still load-bearing: this is prose full of
# $VAR, backticks and ~, and an unquoted heredoc would expand all three,
# turning instructions into whatever this shell happened to have set.
#
# has_post_install() exists because the block may be empty, and an empty
# block must print nothing at all -- not a blank line.
raw_post_install() {
  cat <<'UNFLAB_POST_INSTALL_EOF'
{{POST_INSTALL}}
UNFLAB_POST_INSTALL_EOF
}

has_post_install() {
  [ -n "$(raw_post_install)" ]
}

# Substitute this run's actual install paths into the notes.
#
# The notes tell people what to add to an rc file, so they have to name
# the paths this install used. Printing ~/.local/... to someone who
# passed --prefix /opt/x/bin hands them a line that is wrong in exactly
# the way that gets pasted in anyway and then quietly does nothing.
#
# The rule, which a post-install file can rely on without knowing which
# names are on the list:
#
#   $PREFIX      -> the value        (a name listed below)
#   ${PREFIX}    -> the value
#   $anyother    -> $anyother        (left exactly as written)
#   \$NAME       -> $NAME            (escape consumed, ANY name)
#   \\$PREFIX    -> \<value>         (\\ is a literal backslash and so
#                                     no longer escapes the $)
#
# The escape works on any name rather than only the substituted ones, so
# an author never needs to know the list to protect a `$`. The common
# case needs no escape at all: `fpath=($DATADIR $fpath)` comes out with
# the path filled in and $fpath untouched, because fpath is not a name
# we substitute.
#
# One pass, consuming the whole run of backslashes before a $ so that
# each is judged once: pairs collapse to one literal backslash, and a
# leftover odd one escapes the reference. Separate substitutions could
# not see a run as a unit, and mangled \\\$PREFIX.
#
# Substituted here rather than by letting the shell expand an unquoted
# heredoc, which would take $fpath, backticks and ~ with it -- the
# reason the heredoc is quoted at all.
#
# perl rather than sed, and not because sed cannot: doing it safely in
# sed needs the replacement escaped for & and for the delimiter (a
# --prefix containing & otherwise corrupts, silently, the very path it
# was meant to produce), plus a round trip through a control character,
# because POSIX sed cannot say "replace this except where a backslash
# precedes it". perl says both directly, and an %ENV lookup means a
# value is never reparsed as pattern syntax. /usr/bin/perl is in the
# macOS base system exactly as sed is, and nothing here needs a module.
#
# The export sits inside a subshell so it cannot leak into the rest of
# the script. It is also necessary: a `VAR=x func` prefix does not reach
# a shell FUNCTION's own subprocesses, so perl would see an empty %ENV
# and replace every name with nothing -- which still looks like working
# code while quietly emitting "source /key-bindings.zsh".
print_post_install() {
  (
    echo "$ITALIC"
    export PREFIX BASE MANDIR MAN5DIR MAN8DIR DOCDIR DATADIR CONFDIR \
      UTIL VERSION
    raw_post_install | perl -pe '
      my %ok = map { $_ => 1 }
        qw(PREFIX BASE MANDIR MAN5DIR MAN8DIR DOCDIR DATADIR CONFDIR
           UTIL VERSION);
      s{
        (\\*) \$ (?: \{ (\w+) \} | (\w+) )
      }{
        my ($bs, $braced, $bare) = ($1, $2, $3);
        my $n   = defined $braced ? $braced : $bare;
        my $ref = defined $braced ? "\${$n}" : "\$$n";
        my $lit = "\\" x (length($bs) / 2);
        (length($bs) % 2)
          ? $lit . $ref
          : $lit . ($ok{$n} ? $ENV{$n} : $ref);
      }gex;
    '
    echo "$RESET"
  )
}

# Arguments

# A leading `--` may or may not reach us: `sh -s -- --prefix=x` passes it
# through under sh/dash, while zsh consumes it. Tolerate either.
[ $# -gt 0 ] && [ "$1" = "--" ] && shift

while [ $# -gt 0 ]; do
  case "$1" in
  --prefix)
    PREFIX="$2"
    shift 2
    ;;
  --prefix=*)
    PREFIX="${1#--prefix=}"
    shift
    ;;
  --uninstall)
    ACTION=uninstall
    shift
    ;;
  --purge)
    ACTION=purge
    shift
    ;;
  --no-plain)
    WANT_PLAIN=0
    shift
    ;;
  --quarantine)
    WANT_QUARANTINE_CLEAR=1
    shift
    ;;
  --path)
    PATH_MODE=yes
    shift
    ;;
  --no-path)
    PATH_MODE=no
    shift
    ;;
  -h | --help)
    sed -n '/^# Usage:/,/^$/p' "$0" | sed 's/^# \{0,1\}//'
    exit 0
    ;;
  *)
    echo "$COMMAND$SELF$RESET: ${ERROR}unknown option: $1$RESET" >&2
    exit 2
    ;;
  esac
done

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

# Everything hangs off the prefix's parent, matching the layout the
# package ships: <prefix>/bin, <prefix>/share/man/man1. Passing
# --prefix ~/.local/bin (a bin directory) is the documented interface,
# so derive the others from its parent.
BASE=$(dirname "$PREFIX")
MANDIR="$BASE/share/man/man1"
# Sections 5 and 8 exist for the same reason section 1 does: a daemon's
# page belongs in 8 and its config file's in 5, and `man svnserve`
# only finds them if they are filed correctly.
MAN5DIR="$BASE/share/man/man5"
MAN8DIR="$BASE/share/man/man8"
DOCDIR="$BASE/share/doc/$UTIL"
# Arch-independent files the program reads at run time (btop's themes).
# btop finds these relative to its own binary -- ../share/btop/themes --
# so this layout works under any prefix without a compiled-in path.
DATADIR="$BASE/share/$UTIL"
CONFDIR="${XDG_CONFIG_HOME:-$HOME/.config}/$UTIL"

installed_count=0
removed_count=0
skipped_plain=""
declined_stems=""

# Helpers

# Resolve a manifest `kind` to its destination directory and to whether
# --purge (rather than plain --uninstall) is what removes it.
#
# The three completion kinds write to each shell's conventional
# directory and stop there -- nothing is sourced, enabled or added to
# anyone's rc file. A user whose shell already looks in these places
# gets completion for free, for every unflab package at once; one whose
# shell doesn't sees no change at all. That is the whole contract, and
# it is why these are separate kinds rather than one: the three shells
# disagree about both the directory AND the filename (zsh wants `_fd`
# and reads the `#compdef` tag inside it; bash and fish want `fd`).
#
# zsh has a trap worth knowing: its completion system only picks up a
# directory that was in $fpath when `compinit` ran. Appending to $fpath
# after that line -- the natural thing to write at the bottom of a
# .zshrc -- silently does nothing. Packages that ship a zsh completion
# say so in their post-install notes.
dest_dir_for() {
  case "$1" in
  bin) printf '%s' "$PREFIX" ;;
  man1) printf '%s' "$MANDIR" ;;
  man5) printf '%s' "$MAN5DIR" ;;
  man8) printf '%s' "$MAN8DIR" ;;
  doc) printf '%s' "$DOCDIR" ;;
  data) printf '%s' "$DATADIR" ;;
  config) printf '%s' "$CONFDIR" ;;
  completion-bash) printf '%s' "$BASE/share/bash-completion/completions" ;;
  completion-zsh) printf '%s' "$BASE/share/zsh/site-functions" ;;
  # Same directory as completion-zsh, and deliberately: site-functions
  # is where autoloadable zsh functions live, a completion being one
  # kind of those. A separate kind because the manifest should say
  # which it is -- a completion is picked up by compinit, a plain
  # function needs `autoload -Uz <name>` and does nothing without it.
  function-zsh) printf '%s' "$BASE/share/zsh/site-functions" ;;
  completion-fish) printf '%s' "$BASE/share/fish/vendor_completions.d" ;;
  *) return 1 ;;
  esac
}

# config files are user data: only --purge removes them, never --uninstall.
is_config_kind() { [ "$1" = "config" ]; }

# Remove a path only if we are sure it is ours. Two different rules,
# because we create these two kinds of entry differently:
#
#   remove_own_file  -- a file this package installed at its own name.
#                       A real file there is ours to remove.
#   remove_own_link  -- an unprefixed alias. We only ever create these as
#                       symlinks pointing at our own $dest, so a symlink
#                       elsewhere, or a REAL FILE, belongs to someone else
#                       and must be left strictly alone. Getting this
#                       wrong deletes another package's binary.
remove_own_file() {
  target="$1"

  # If it exists, or is a symlink, it's ours to remove.
  # XXX: is this right? Doesn't `-e` cover `-L`?
  [ -e "$target" ] || [ -L "$target" ] || return 0

  # Remove it.
  rm -f "$target"
  echo "Removed $target"
  removed_count=$((removed_count + 1))
}

remove_own_link() {
  target="$1"
  expect="$2"
  # Not a symlink (missing, or a real file someone else owns) -> not ours.
  [ -L "$target" ] || {
    [ -e "$target" ] && echo "Kept $target (not ours: real file, not our symlink)"
    return 0
  }

  # If it's a symlink, check it points at the expected thing.
  link=$(readlink "$target")
  case "$link" in
  "$expect" | */"$expect") ;;
  *)
    echo "Kept $target (not ours: points at $link)"
    return 0
    ;;
  esac

  # Remove it.
  rm -f "$target"
  echo "Removed $target"
  removed_count=$((removed_count + 1))
}

# Uninstall / purge

if [ "$ACTION" = uninstall ] || [ "$ACTION" = purge ]; then

  # Fed by heredoc, NOT by a pipe: `echo "$MANIFEST" | while ...` runs the
  # loop in a subshell, so removed_count would be discarded and the
  # summary below would always report 0.

  # Read the manifest, one line at a time.
  while IFS='	' read -r kind mode src dest plain; do

    # Skip empty lines and comments.
    case "$kind" in '' | \#*) continue ;; esac

    # Get the destination directory for this kind.
    dir=$(dest_dir_for "$kind") || continue

    # Config files survive --uninstall; only --purge takes them.
    if is_config_kind "$kind" && [ "$ACTION" != purge ]; then

      # If it exists, it's kept. If not, we just don't mention it.
      [ -e "$dir/$dest" ] && echo "Kept $dir/$dest (use --purge to remove)"
      continue
    fi

    # The plain-named alias first: it points at $dest, so verify before
    # removing the thing it points to.
    [ "$plain" != "-" ] && [ -n "$plain" ] && remove_own_link "$dir/$plain" "$dest"
    [ "$dest" != "-" ] && [ -n "$dest" ] && remove_own_file "$dir/$dest"

  done <<UNFLAB_EOF
$MANIFEST
UNFLAB_EOF

  # Only prune directories we own, and only when empty -- never $PREFIX
  # or $MANDIR, which belong to the user and hold other tools' files.
  # $DATADIR is listed after its own subdirectories: rmdir only removes
  # an empty directory, so themes/ has to go before share/btop/ can.
  # man5/man8 are pruned but man1 is not: man1 almost certainly holds
  # other tools' pages, while these two are usually ours alone. rmdir
  # refuses a non-empty directory either way, so this is safe.
  # The completion directories are pruned on the same terms: rmdir
  # refuses a non-empty one, so another package's (or the user's own)
  # completions there keep it alive.
  for d in "$DATADIR"/* "$DATADIR" "$DOCDIR" "$CONFDIR" \
    "$MAN5DIR" "$MAN8DIR" \
    "$BASE/share/bash-completion/completions" \
    "$BASE/share/bash-completion" \
    "$BASE/share/zsh/site-functions" "$BASE/share/zsh" \
    "$BASE/share/fish/vendor_completions.d" "$BASE/share/fish"; do
    # If it exists, try to remove it. If it has contents, it'll fail.
    # If it doesn't exist, we don't mention it.
    [ -d "$d" ] && rmdir "$d" 2>/dev/null && echo "Removed empty $d"
  done

  # If nothing was removed, say so.
  if [ "$removed_count" = 0 ]; then
    echo "Nothing to remove for $UTIL under $BASE."
  else
    echo ""
    echo "Removed $removed_count file(s) for $UTIL."
  fi
  exit 0
fi

# Install

# Read the manifest, one line at a time.
while IFS='	' read -r kind mode src dest plain; do

  # Skip empty lines and comments.
  case "$kind" in '' | \#*) continue ;; esac

  # Get the destination directory for this kind.
  dir=$(dest_dir_for "$kind") || {
    echo "install.sh: unknown kind '$kind'" >&2
    exit 1
  }

  # If the dest isn't set (or is -), skip it.
  [ "$dest" = "-" ] || [ -z "$dest" ] && continue

  # If the src isn't there, fail
  if [ ! -f "$SCRIPT_DIR/$src" ]; then
    echo "install.sh: missing from package: $src" >&2
    exit 1
  fi

  # A config file is user data: never clobber one the user has edited.
  if is_config_kind "$kind" && [ -e "$dir/$dest" ]; then
    echo "Kept existing $dir/$dest (not overwritten)"
    continue
  fi

  # Install the file. A dest may name a subdirectory (btop's
  # themes/<name>.theme), so create the parent of the destination
  # rather than just $dir -- dirname gives back "." for a plain name,
  # which makes this the same operation in the common case.
  install -d -m 755 "$dir/$(dirname "$dest")"
  install -m "$mode" "$SCRIPT_DIR/$src" "$dir/$dest"
  echo "Installed $dir/$dest"
  installed_count=$((installed_count + 1))

  # The unprefixed alias, decided live on THIS machine rather than at
  # build time: claim the plain name only if nothing else answers to it.
  # `command -v` sees the real PATH, which is the only correct authority
  # on whether a name is already taken here.
  #
  if [ "$WANT_PLAIN" = 1 ] && [ "$plain" != "-" ] && [ -n "$plain" ]; then

    # If it's a binary, check it's not already installed.
    if [ "$kind" = bin ]; then

      # If the plain command exists...
      #
      # `|| existing=""` is load-bearing: command -v exits non-zero when
      # the name is free, and under `set -e` a bare assignment from it
      # kills the script mid-install -- silently, with status 0. That is
      # exactly the common case here (a free name is why we'd claim it),
      # so without this, installing timeout stops after gtimeout and
      # never creates the plain symlink.
      existing=$(command -v "$plain") || existing=""
      if [ -n "$existing" ]; then

        # If installed to the same location, it's probably one of our earlier installs
        if [ "$existing" != "$dir/$plain" ]; then

          skipped_plain="$skipped_plain $plain"
          # Remember the *stem* so this binary's man page (and anything
          # else named after it) follows the same decision below.
          declined_stems="$declined_stems ${plain} "
          continue
        fi
      fi

    else
      # Non-binary kinds follow whatever the binary decided. `man demo`
      # must work exactly when a plain `demo` command exists to be asked
      # about -- otherwise we'd document a tool the user isn't running.
      stem=${plain%%.*}
      case "$declined_stems" in
      *" $stem "*)
        echo "Skipped $dir/$plain (plain '$stem' not claimed)"
        continue
        ;;
      esac
    fi

    # Relative target: the link sits beside its destination, so it keeps
    # resolving if the prefix is later moved, renamed, or reached by
    # another path (a symlinked home, a relocated tree).
    ln -sf "$dest" "$dir/$plain"
    echo "Installed $dir/$plain -> $dest"
  fi
done <<UNFLAB_EOF
$MANIFEST
UNFLAB_EOF

# Quarantine

# Binaries here aren't signed with an Apple Developer ID or notarized, so
# if this package arrived via a browser (or anything else LaunchServices
# knows about) macOS will refuse to run it.
#
# `install` copies extended attributes along with the file, so the flag
# follows the binary to its destination -- which is why this is checked
# here, after the copy, and reported against the path you'll actually invoke.
#
# Downloads made by curl are NOT quarantined, so the `curl | sh` install
# path shouldn't trigger this. It's the manual-download route that does.
#
# We don't clear it silently; it's not our place to do so without permission.

# If we have xattr (we damn well ought to), check the quarantine flag.
if command -v xattr >/dev/null 2>&1; then
  quarantined=""

  # Read the manifest, one line at a time.
  while IFS='	' read -r kind mode src dest plain; do

    # Skip empty lines and comments.
    case "$kind" in '' | \#*) continue ;; esac

    [ "$kind" = bin ] || continue # Only quarantine binaries
    [ "$dest" = "-" ] && continue # Skip if no destination

    # If the binary is quarantined, note it.
    if xattr -p com.apple.quarantine "$PREFIX/$dest" >/dev/null 2>&1; then

      # If we're supposed to clear it, do so.
      if [ "$WANT_QUARANTINE_CLEAR" = 1 ]; then

        # Clear it.
        xattr -d com.apple.quarantine "$PREFIX/$dest" 2>/dev/null || true
        echo "Cleared com.apple.quarantine from $PREFIX/$dest"

      else
        # Otherwise, note it.
        quarantined="$quarantined $dest"
      fi
    fi
  done <<UNFLAB_EOF
$MANIFEST
UNFLAB_EOF

  # If we found any, tell the user.
  if [ -n "$quarantined" ]; then
    echo "$BOLD$MAGENTA"
    echo "Note: macOS has quarantined the installed binary, and Gatekeeper"
    echo "      will block it. Re-run with $YELLOW--quarantine$RESET, or clear it yourself:"
    echo "$RESET"

    for q in $quarantined; do
      echo "          ${COMMAND}xattr ${FLAG}-d com.apple.quarantine ${PARAM}'$PREFIX/$q'$RESET"
    done

    echo ""
  fi
fi

# PATH management

# Only PATH needs managing: macOS's `man` derives its own search path from
# PATH, finding <prefix>/../share/man automatically, so a working PATH
# gets the man pages for free and MANPATH never needs touching.
# This is somehting I never realised about macOS before...

# If the PATH contains the prefix, it's good.
case ":$PATH:" in
*":$PREFIX:"*) PATH_ALREADY=1 ;;
*) PATH_ALREADY=0 ;;
esac

# If PATH doesn't include our prefix, and we installed something, offer to fix it.
if [ "$PATH_ALREADY" = 0 ] && [ "$installed_count" -gt 0 ]; then

  # Pick the rc file for the user's login shell, not for whatever shell
  # happens to be running this script.
  case "${SHELL:-}" in
  */zsh) RC="${ZDOTDIR:-$HOME}/.zshrc" ;;
  */bash) RC="$HOME/.bash_profile" ;;
  */fish) RC="$HOME/.config/fish/config.fish" ;;
  *) RC="$HOME/.profile" ;;
  esac

  # Prepare the line that may (or may not) be added.
  case "$RC" in
  */config.fish) LINE="fish_add_path $PREFIX" ;;
  *) LINE="export PATH=\"$PREFIX:\$PATH\"" ;;
  esac

  echo ""
  echo "${PARAM}$PREFIX${RESET} ${WARNING}is not on your PATH, so ${COMMAND}'$UTIL'$RESET ${WARNING}won't be found by name yet.$RESET"

  # Ask the user if they want to add the line to the rc file.
  DO_PATH=0

  if [ "$PATH_MODE" = yes ]; then
    # The user's already said --path, so we're good.
    DO_PATH=1

  elif [ "$PATH_MODE" = ask ] && [ "$TTY_OK" = 1 ]; then
    # We're in 'ask' mode and managed to get an interactive terminal.
    # So, let's ask the user.
    echo "" >&3
    echo "  Add this line to $RC?" >&3
    echo "      $LINE" >&3
    printf '  [y/N] ' >&3
    IFS= read -r reply <&3 || reply=""

    # If they said yes, we're good.
    case "$reply" in y | Y | yes | YES) DO_PATH=1 ;; esac
  fi

  # If they decided to add the line, do so.
  if [ "$DO_PATH" = 1 ]; then

    # A marked block, so it's obvious who added this and easy to remove.
    {
      echo ""
      echo "# added by Unflab, initially for $UTIL - https://unflab.app"
      echo "$LINE"
    } >>"$RC"
    echo "Added to $RC. Run:  . $RC   (or open a new terminal)"

  else
    echo ""
    echo "  To fix, add this to $RC:"
    echo "      $LINE"
    echo ""
    echo "  Or run it now for this shell only:"
    echo "      $LINE"
  fi
fi

# Summary

echo ""
if [ -n "$skipped_plain" ]; then
  for p in $skipped_plain; do
    echo "Note: '$p' already exists on this system ($(command -v "$p"))."
    echo "      Left it alone; use the installed name instead."
  done
  echo ""
fi

echo "$UTIL $VERSION installed ($installed_count file(s)) under $BASE."

# After the summary, so the count is read first and the notes are the
# last thing left on screen. Only on install: a note telling you how
# to set something up is noise when you have just removed it.
if has_post_install; then
  echo ""
  print_post_install
fi
