# gettext -- GNU envsubst, from the gettext runtime tools
#
# Class 2 (suite extraction). `brew install gettext` builds the whole of
# GNU gettext: 22 executables, libintl, libasprintf, libtextstyle, the
# Emacs Lisp files and the manual, against json-c and libunistring. This
# builds one 93 KB binary out of that, linking libSystem alone.
#
# macOS ships no envsubst, no gettext, and no libintl at all. The only
# thing with a similar name is /usr/bin/xgettext.pl, a Perl
# Locale::Maketext tool unrelated to GNU gettext -- so nothing here
# shadows anything, and there is no system copy to fall back on.
#
# Homebrew's gettext is really a *library* formula: dozens of other
# formulae depend on it for libintl, and envsubst arrives as a side
# effect of that. This inverts it -- the sh utility is the point, and
# the library is what gets left behind.
#
# Only envsubst is packaged, though the recipe is set up to ship more of
# the runtime tools if a reason appears. The other four (gettext,
# ngettext, printf_gettext, printf_ngettext) look up strings in .mo
# message catalogues, and nothing on a Mac installs catalogues where
# they would find them, so they would be four binaries that do little
# but echo their argument back. envsubst is the one that works with no
# catalogue at all, because it substitutes environment variables rather
# than translations.
#
# gettext-tools -- msgfmt, msgmerge, xgettext and the rest -- is a
# separate 5.5 MB proposition needing libunistring and libxml2, and
# serves translators rather than shell users. See utils/NOT-SHIPPED.md.

UNFLAB_NAME=gettext
UNFLAB_VERSION=1.0
UNFLAB_HOMEPAGE=https://www.gnu.org/software/gettext/
UNFLAB_LICENSE=GPL-3.0-or-later
UNFLAB_SOURCE=https://ftp.gnu.org/gnu/gettext/gettext-1.0.tar.gz
UNFLAB_CHECK=gnu:gettext
UNFLAB_SHA256=85d99b79c981a404874c02e0342176cf75c7698e2b51fe41031cf6526d974f1a
UNFLAB_ATTEST=gnupg:https://ftp.gnu.org/gnu/gnu-keyring.gpg
UNFLAB_TOOLCHAIN="c autotools make"
UNFLAB_CLASS=2
UNFLAB_PACKAGES=envsubst

unflab_build() {
  # Built in the gettext-runtime subdirectory rather than at the top of
  # the tree. Upstream's own PACKAGING file recommends exactly this
  # split -- "the runtime programs are utilities for sh programs", 420
  # KB against gettext-tools' 5.5 MB. Configuring at the top level
  # would build both, which is the bulk this package exists to avoid.
  #
  # Both phases run under `cd "$BUILD_DIR"`, so this relative cd applies
  # to the build only; unflab_stage does its own (separate subshell).
  cd gettext-runtime

  # --disable-nls is the usual trade (pv, coreutils, wget), and it is
  # doubly apt here: it stops gettext-runtime building translations of
  # its own messages, which is what would drag in the libintl this
  # package is trying not to ship.
  #
  # --disable-shared leaves no dylibs to install or relocate. Only the
  # binary is staged, so a shared libintl would be dead weight the gate
  # would reject anyway.
  #
  # The language bindings are each switched off explicitly. configure
  # probes for a JDK, a C# runtime, a D compiler and GNU Modula-2, and
  # would build libintl.jar or GNU.Gettext.dll if it found any -- none
  # of which belongs in a package shipping one C binary. Turning them
  # off also keeps the build the same on a machine that happens to have
  # a JDK installed.
  #
  # --without-git and --without-cvs are for autopoint, which lives in
  # gettext-tools and is not built here; they stop configure recording
  # paths to whatever VCS the build machine has.
  ./configure \
    --disable-nls \
    --disable-shared \
    --disable-java \
    --disable-csharp \
    --disable-d \
    --disable-modula2 \
    --without-git \
    --without-cvs \
    --without-emacs \
    >/dev/null
  make
}

unflab_stage() {
  # Runs once per entry in UNFLAB_PACKAGES, with $PKG set. Only envsubst
  # is listed today; the paths below are keyed on $PKG so adding a
  # sibling runtime tool needs a UNFLAB_PACKAGES entry and a <pkg>.tsv,
  # nothing here.
  #
  # A separate subshell from unflab_build, so its `cd` did not survive.
  cd gettext-runtime

  install -d "$STAGE_DIR/bin" "$STAGE_DIR/share/man/man1"
  install -m 755 "src/$PKG" "$STAGE_DIR/bin/$PKG"

  # envsubst.1 ships pre-written in the tarball. The other four runtime
  # man pages are generated by make from .1.in templates that also ship,
  # so neither case needs help2man at build time.
  install -m 644 "man/$PKG.1" "$STAGE_DIR/share/man/man1/$PKG.1"

  # COPYING is at the top of the tree, one level up from gettext-runtime.
  install -m 644 ../COPYING "$STAGE_DIR/LICENSE"
  install -m 644 "$RECIPE_DIR/README-$PKG.md" "$STAGE_DIR/README.md"
}
