# duti -- set default apps for file types and URL schemes
#
# Class 3 (convenience): duti's Homebrew formula has no runtime
# dependencies either, so there is no dependency tree to escape. It is
# here because macOS ships nothing that does this -- Launch Services
# associations are otherwise a Finder Get Info dialog, one file type at
# a time, with no way to script them.
#
# What this build does have over Homebrew's is a newer macOS. Upstream
# was last released in 2018 and its configure has a hardcoded list of
# Darwin versions, erroring out on anything past darwin17 (10.13). Every
# one of Homebrew's five backported patches exists to append another
# version to that case statement, and Homebrew *still* needs an
# inreplace on top because the patches trail each macOS release.
#
# So this doesn't carry the patches. It neutralises the version check
# once and passes the SDK and deployment target explicitly, which is
# what Homebrew's inreplace ends up doing anyway -- and it keeps working
# on a macOS nobody has patched for yet, which was the whole problem.
#
# The build is otherwise stock. duti links ApplicationServices,
# CoreFoundation and CoreServices, all in /System/, so nothing needs
# unpicking to satisfy the gate.
#
# dutis ships in the same package. It's a separate Rust project
# (tsonglew/dutis) that reads Launch Services natively but makes every
# change by running `duti` from PATH -- so a dutis package on its own
# would either be broken or need a dependency, and unflab doesn't do
# dependencies. One package, both tools, and they can't get out of
# step. Its companion dutis-event-http ships too, as upstream's own
# Homebrew tap does.

UNFLAB_NAME=duti
UNFLAB_VERSION=1.5.4
UNFLAB_HOMEPAGE=https://github.com/moretension/duti/
UNFLAB_LICENSE="public-domain AND MIT"
UNFLAB_SOURCE=https://github.com/moretension/duti/archive/refs/tags/duti-1.5.4.tar.gz
UNFLAB_CHECK=github-tags:moretension/duti
UNFLAB_SHA256=3f8f599899a0c3b85549190417e4433502f97e332ce96cd8fa95c0a9adbe56de
UNFLAB_ATTEST='none:GitHub auto-generated tag archive; upstream published no release assets and has been dormant since 2018'
UNFLAB_TOOLCHAIN="c autotools make rust cargo"
UNFLAB_CLASS=3

# The tag is duti-1.5.4, so the archive unpacks to duti-duti-1.5.4
# rather than the duti-1.5.4 that build.sh derives from name and
# version.
UNFLAB_SRC_DIR="$BUILD_ROOT/duti-duti-$UNFLAB_VERSION"

# The second source. UNFLAB_DUTIS_CHECK is what makes check-updates.sh
# watch it: dutis releases often, where duti hasn't moved since 2018.
UNFLAB_DUTIS_VERSION=2.24.0
UNFLAB_DUTIS_SOURCE="https://github.com/tsonglew/dutis/archive/refs/tags/v$UNFLAB_DUTIS_VERSION.tar.gz"
UNFLAB_DUTIS_SHA256=5bb5cd810d984f396136aed4378b65b77d45fd752432f7f06935b376e6a3ea92
UNFLAB_DUTIS_CHECK=github:tsonglew/dutis
UNFLAB_DUTIS_DIR="$BUILD_ROOT/dutis-$UNFLAB_DUTIS_VERSION"

unflab_build() {
  # Upstream ships no configure script: it is generated by the Makefile's
  # `dist` target when a release tarball is rolled, and this builds from
  # the git tag archive, which predates that step. Hence autoconf.
  #
  # Two substitutions have to happen before it runs, both of them things
  # `dist` would have done:

  # 1. The SDK check refuses to run on any Darwin newer than 17 (macOS
  #    10.13). Replacing the fatal error with the same assignment
  #    its supported branches make leaves the rest of the macro intact:
  #    --with-macosx-sdk below still supplies the path, and clearing
  #    macosx_arches drops the hardcoded `-arch i386 -arch x86_64`,
  #    which would otherwise cross-build for Intel on Apple Silicon.
  #    This is exactly Homebrew's inreplace, for the same reason.
  sed -i.bak \
    's|AC_MSG_ERROR(\[${host_os} is not a supported system\])|macosx_arches=""|' \
    aclocal.m4

  # 2. AC_INIT hardcodes the version as the literal string INTERNAL,
  #    which `dist` seds to the real number on its way out. Without
  #    this, `duti -V` prints "INTERNAL" -- as Homebrew's build does.
  sed -i.bak \
    "s|AC_INIT(dh, INTERNAL,|AC_INIT(dh, $UNFLAB_VERSION,|" \
    configure.ac

  autoconf

  # The SDK path and deployment target are passed explicitly because the
  # macro can no longer derive them: its case statement knows nothing
  # about this Darwin, which is the point of the patch above. xcrun
  # answers for whatever SDK is actually installed.
  ./configure \
    --with-macosx-sdk="$(xcrun --show-sdk-path)" \
    --with-macosx-deployment-target="$(sw_vers -productVersion)" \
    >/dev/null
  make

  # --- dutis ----------------------------------------------------------
  # Fetched and checked here rather than by build.sh, which handles one
  # source per recipe; rdfind does the same for nettle.
  local tarball="$BUILD_ROOT/dutis.tar.gz" actual
  curl -fsSL --connect-timeout 15 --max-time 300 --retry 2 \
    -o "$tarball" "$UNFLAB_DUTIS_SOURCE"
  actual="$(shasum -a 256 "$tarball" | awk '{print $1}')"
  if [ "$actual" != "$UNFLAB_DUTIS_SHA256" ]; then
    echo "duti recipe: dutis checksum mismatch" >&2
    echo "  expected: $UNFLAB_DUTIS_SHA256" >&2
    echo "  actual:   $actual" >&2
    return 1
  fi
  rm -rf "$UNFLAB_DUTIS_DIR"
  tar xzf "$tarball" -C "$BUILD_ROOT"

  # --locked builds against the committed Cargo.lock rather than
  # whatever crates.io resolves today. The Launch Services calls link
  # CoreFoundation and CoreServices, both in /System/.
  ( cd "$UNFLAB_DUTIS_DIR" && cargo build --release --locked )
}

unflab_stage() {
  install -d "$STAGE_DIR/bin" "$STAGE_DIR/share/man/man1"
  install -m 755 duti "$STAGE_DIR/bin/duti"

  # The man page carries a _DUTI_BUILD_DATE placeholder that `dist`
  # fills in, so shipping duti.1 verbatim puts that literal string in
  # the header (which is what Homebrew's package does). Substituted
  # with the upstream release's own date rather than today's: the build
  # key hashes what a recipe produces, and a date that moved every run
  # would rebuild this package on every release for no reason.
  sed 's|_DUTI_BUILD_DATE|April 13, 2018|' duti.1 \
    > "$STAGE_DIR/share/man/man1/duti.1"
  chmod 644 "$STAGE_DIR/share/man/man1/duti.1"

  # COPYRIGHT is the licence: duti is public domain, so there is no
  # COPYING or LICENSE file, and this three-line note is the whole of
  # the terms.
  install -m 644 COPYRIGHT "$STAGE_DIR/LICENSE"
  install -m 644 "$RECIPE_DIR/README.md" "$STAGE_DIR/README.md"

  install -m 755 "$UNFLAB_DUTIS_DIR/target/release/dutis" "$STAGE_DIR/bin/dutis"
  install -m 755 "$UNFLAB_DUTIS_DIR/target/release/dutis-event-http" \
    "$STAGE_DIR/bin/dutis-event-http"

  # dutis's repo has no LICENSE file. Cargo.toml declares MIT, and the
  # project's site (website/index.html in this same tarball) carries
  # "(c) 2026 Tsonglew . MIT License"; LICENSE-dutis is the standard
  # MIT text with that notice, since MIT requires one to be shipped.
  install -m 644 "$RECIPE_DIR/LICENSE-dutis" "$STAGE_DIR/LICENSE-dutis"

  # No man page or completions upstream -- `dutis --help` and its
  # per-command help are the documentation.
}
