# fd -- a fast, user-friendly alternative to find
#
# Class 3 (convenience): fd's only Homebrew dependency is rust, at build
# time, so there is no dependency tree to escape and upstream publishes
# prebuilt macOS binaries. It's here because it belongs in the same
# one-line shape as everything else.
#
# What it does replace is `find`, which macOS ships -- so the honest
# pitch is ergonomics, not availability: sensible defaults, regex
# matching, .gitignore awareness and parallel traversal, against find's
# predicate syntax. Nobody is stuck without it.
#
# Pure Rust, and nothing in the dependency tree reaches for a system
# library: no -sys crates beyond libc, and jemalloc is explicitly
# excluded on macOS by the target cfg in Cargo.toml (upstream disabled
# it there over a Catalina bug, issue #498). That is why this needs
# none of the coaxing typst's recipe documents, and why Homebrew's
# JEMALLOC_SYS_WITH_LG_PAGE line is guarded to Linux. The gate proves
# it rather than taking it on trust.
#
# Dual-licensed MIT OR Apache-2.0. Both licence files ship: upstream
# offers the choice and dropping one would misrepresent the terms.

UNFLAB_NAME=fd
UNFLAB_VERSION=10.5.0
UNFLAB_HOMEPAGE=https://github.com/sharkdp/fd
UNFLAB_LICENSE="MIT OR Apache-2.0"
UNFLAB_SOURCE=https://github.com/sharkdp/fd/archive/refs/tags/v10.5.0.tar.gz
UNFLAB_CHECK=github:sharkdp/fd
UNFLAB_SHA256=e6d9e90730bf316101691e49d59cc02565278dc3779d33a77423801569484851
UNFLAB_ATTEST='none:GitHub auto-generated tag archive; upstream publishes prebuilt binaries but no checksum for the source'
UNFLAB_TOOLCHAIN="rust cargo"
UNFLAB_CLASS=3
UNFLAB_PACKAGES=fd

unflab_build() {
  # --locked builds against the committed Cargo.lock rather than
  # re-resolving, so every crate is pinned by the hash upstream tested
  # -- the same bargain typst and doggo make for a build that fetches
  # over the network.
  #
  # The `completions` feature is on by default and is what makes
  # `fd --gen-completions` work; the staging phase uses it.
  cargo build --release --locked
}

unflab_stage() {
  install -d "$STAGE_DIR/bin" "$STAGE_DIR/share/man/man1" \
             "$STAGE_DIR/completion"
  install -m 755 target/release/fd "$STAGE_DIR/bin/fd"
  install -m 644 doc/fd.1 "$STAGE_DIR/share/man/man1/fd.1"

  # Dual-licensed: ship both, since the choice is the user's to make.
  install -m 644 LICENSE-MIT "$STAGE_DIR/LICENSE-MIT"
  install -m 644 LICENSE-APACHE "$STAGE_DIR/LICENSE-APACHE"
  install -m 644 "$RECIPE_DIR/README.md" "$STAGE_DIR/README.md"

  # zsh's completion is hand-written and shipped in the tree; bash and
  # fish are generated by the binary we just built, which is also what
  # Homebrew does. Generating them from the built binary keeps the
  # flags in the completion and the flags in the binary in step.
  #
  # Not shipped: contrib/completion/_fdfind, a two-line shim for
  # Debian's renamed `fdfind` binary, which this package doesn't install.
  install -m 644 contrib/completion/_fd "$STAGE_DIR/completion/_fd"

  ./target/release/fd --gen-completions bash > "$STAGE_DIR/completion/fd.bash"
  ./target/release/fd --gen-completions fish > "$STAGE_DIR/completion/fd.fish"

  # A silently empty completion would install fine and do nothing, so
  # check rather than trust: --gen-completions is behind a cargo feature
  # that is on by default today but need not stay that way.
  for f in "$STAGE_DIR/completion/fd.bash" "$STAGE_DIR/completion/fd.fish"; do
    [ -s "$f" ] || {
      echo "fd: $f is empty -- did the 'completions' feature go away?" >&2
      return 1
    }
  done

  # Shell integration does nothing until the user's shell is looking in
  # these directories, and zsh in particular needs fpath set before
  # compinit runs -- so say so rather than let it look like it failed.
  install -m 644 "$RECIPE_DIR/caveats.txt" "$STAGE_DIR/.unflab/caveats.txt"
}
